### ISSUE TITLE
Some tags on the repository would be helpful

### ISSUE THREAD

**Issue by ggothe** [itribe/typoscript_code#14]
so i can reference a version besides dev-master using composer
eg
```
git tag 5.0.0 3353fe6
git tag 6.0.0 ff4e697
git tag 6.1.0 eed65d5
git tag 6.2.0 f306acf
git push --tags
```

**Comment by itribe** [comment]
Thank you Goddart.
We added tags and published the extension to Packagist.
Hopefully it will suit your workflow now.

**Comment by ggothe** [comment]
works like a charm!
