### ISSUE TITLE
Compatibility with Typo3 v11?

### ISSUE THREAD

**Issue by baden32** [itribe/typoscript_code#15]
Dear Anton,
Do you think this extension could be used with Typo3 version 11? Or changes are necessary?
Thank you in advance for your job and reply.
Bads

**Comment by danilovq** [comment]
@baden32 Thanks for reporting the issue. Unfortunately, the extension will not work with TYPO3 11 out of the box. We planned to release the v11 compatible version but had no resources recently. We will do our best and try to make a release asap. Keep tune!

**Comment by danilovq** [comment]
@baden32 TYPO3 11 compatible version is released. Please check.

**Comment by baden32** [comment]
Dear Anton
Thanks a lot for your job, the new version works fine with Typo3 v11, great!
Cheers,
Bads
