### ISSUE TITLE
Problem with TYPO3 Version 7.6.12

### ISSUE THREAD

**Issue by hoermannklaus** [itribe/typoscript_code#2]
I encountered a problem using this extension with the newest TYPO3 version 7.6.12. The ExtensionManager throws an error about the suggests section of the ext_emconf.php.

I guess the integer key for the array is what TYPO3 does not like. When removed everything works fine. 

I refer to the TYPO3 documentation, where examples always have a string key: [TYPO3 Documentation: Declaration file](https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/DeclarationFile/Index.html)

**Comment by danilovq** [comment]
New version released to TER. Thanks for reporting this issue.
