### ISSUE TITLE
Add example to documentation with using constants?

### ISSUE THREAD

**Issue by mickenorlen** [itribe/typoscript_code#9]
Sorry, this isn't reallly an issue, i didn't know where else to ask.

You say:

"Code could access definitions from website TypoScript templates, as well as constants."

How do i access the constants from templates or extension setup.ts? Can you give an example? For some reason i cant get it to work even if i include the typoscript explicitly in the content element. Also, I would like to know if it is possible to add for example includeJSFooter statements to the page?

Thanks a lot for this great extension! =)

**Comment by itribe** [comment]
@mickenorlen here is the example.
I have an empty TYPO3 8.7 installation. There are constants included by "fluid_styled_content" extension by default.
![example_1_170606125312](https://cloud.githubusercontent.com/assets/14820846/26819176/2ba3909c-4ab7-11e7-9a6b-e4ce21915b31.png)
I inserted "TypoScript code" content element on page with the following code:
```
10 = IMAGE
10 {
  file = fileadmin/Backimage.jpg
  file.width = 100c
  file.height = 100c
  imageLinkWrap = 1
  imageLinkWrap {
    enable = 1
    file = fileadmin/Backimage.jpg
    bodyTag = <body style="margin:0; background:#fff;">
    wrap = <a href="javascript:close();"> | </a>
    width = {$styles.content.textmedia.linkWrap.width}
    height = {$styles.content.textmedia.linkWrap.height}
    JSwindow = 1
    JSwindow {
    newWindow = {$styles.content.textmedia.linkWrap.newWindow}
      if.isFalse = {$styles.content.textmedia.linkWrap.lightboxEnabled}
    }
    directImageLink = {$styles.content.textmedia.linkWrap.lightboxEnabled}
    linkParams.ATagParams.dataWrap =  class="{$styles.content.textmedia.linkWrap.lightboxCssClass}" rel="{$styles.content.textmedia.linkWrap.lightboxRelAttribute}"
  }
}
```
The result is the followng:
![example_2_170606130359](https://cloud.githubusercontent.com/assets/14820846/26819513/aa585688-4ab8-11e7-95ff-0d66d8dc7a5d.png)

**Comment by mickenorlen** [comment]
Thank you so much for this quick reply. I'm realizing that your extension is really helpful for learning how typoscript works =)
